### ISSUE TITLE
Disable hash on first start / Multiple Tabbed Content Issue

### ISSUE THREAD

**Issue by Skinwalker** [elboletaire/tabbedcontent#24]
Is it possible to disabled the hash if i open the page for the first time?

Problem is:
When i have multiple tabbed contents, always the first tablink hash of the last tab container is added to the url ...
Same problem occurs in the multiple tabbed contents demo

This problem can be fixed by not adding the hash to the url if theres no hash present.

**Comment by elboletaire** [comment]
And why is that a problem? :confused:

**Comment by Skinwalker** [comment]
Because when i open the page i get a hashtag added which is not the first.

That might be a little confusing to the visitors ( i'm confused ;) )

Maybe i can remove the hashtag with the onInit Callback?

**Comment by elboletaire** [comment]
No, you can't.

My experience tells me that visitors do not pay attention to the address bar.. in fact, half of them do not know what an "address bar" is #truestory

I don't remember how did I developed this exactly, but I think that you can change this easily. 

You are free to change it, and to make a pull request (in case you find a solution) but I think that this is not a feature that does not need to be implemented at all (as said, visitors do not pay attention to the address bar, except for developers like us).

**Comment by elboletaire** [comment]
I accidentally said that it would be easy when it won't be. I've changed it, but if you are reading issues through the email you wouldn't see the change.

**Comment by Skinwalker** [comment]
Found a problem ...

If you open the site on a tablet / phone and refresh the site without clicking any tab-link the site will jump the last tab-content.
On my site its on the very end of the page :(

I will try to look at your code to remove the first hash adding (maybe via onInit Callback)

**Comment by elboletaire** [comment]
Users do not usually refresh the page... that's another thing that we (developers) do a lot, but as said before... "normal people" do not do that kind of things. "Normal people" just use one tab at a time (and when they use two at a time is because they lost track of the first one), do not use the address bar for anything except typing "google" (of course without the dot com) and that kind of things.

But as said, if you find a fix for this I'll be glad to accept the PR :smiley: 

Good luck!

**Comment by revivemarketing** [comment]
@elboletaire I'm not sure where you gathered the knowledge that 'users do not usually refresh pages' or that 'visitors do not pay attention to the address bar' ... I'm impressed with the plugin you created but am baffled by your lack of experience with regards to user experience. 

If you're not developing this to improve the user experience, then keep it a private repo.. when you open it to the public you are, in effect, saying that it's your contribution to helping improve the user experience of others.

I personally know tons of professionals outside the UI, UX and Development industry that would say those statements are patently false. 

I don't say this to offend.. to the contrary I hope that this sparks some introspection and preferably a consideration to change your perspective on this.

Having a hashtag when a page loads is a major User Experience issue - especially when the page scrolls TO THAT HASHTAG :) That creates a very undesirable effect.

Again, great work on the plugin and I'll keep watching in the hopes that you, or another contributor, can provide a workable solution so the initial hashtag is not needed.

**Comment by elboletaire** [comment]
Man, I've too much work to discuss with you. 

The only thing am gonna say is... instead of speaking that loud, why not PR my project and fix it by yourself? You say a lot about open source but you could do it by yourself.

Anyway, I don't find this to be an issue, except for some browsers like Safari (it works well under Firefox and Chrome, both for mobile and desktop), which I cannot test because I don't have a Mac, and I'm not gonna purchase one (nor I'm gonna create a VM just to test this).

If this is an issue for you, then PR it and, if the changes LGTM, I'll merge them. But stop complaining if you don't want to help.

**Comment by revivemarketing** [comment]
Wow,. nice response. As I mentioned, I'm a UX Engineer by profession. If I could code this fix and PR it, I would gladly do it. Although it is a contribution to help correct a misconception on the part of the developer who's wholly missing the impact their oversight is having on users. 
It's totally up to you how you wish to address it.. though, I'll be honest and didn't expect you to basic say, 'I don't plan on developing this fully and if you can't fix what I did wrong, then stay out of it'.

I hope maybe you'll reconsider. As for my use case, I modified your code - though I'm no JS developer I do ok with finding solution - but since I have not tested it thoroughly nor really know how to unit test JS code... it'll likely never go anywhere but where I'm using it.

**Comment by elboletaire** [comment]
> I don't plan on developing this fully and if you can't fix what I did wrong, then stay out of it

Never said that.

As said, I don't have time to discuss as much as I want.

If you have a workaround for the issue on whatever browser you're trying, share it with us and I'll try to add it to the code if it LGTM.
